### ISSUE TITLE
Ability to renderBadge()

### ISSUE THREAD

**Issue by grabbou** [exponentjs/ex-navigation#102]
https://github.com/exponentjs/ex-navigation/blob/f5cf2d278d84310f6517a6af1136ae5e01b4f961/src/tab/ExNavigationTabBar.js#L64-L69

Instead of specifying a badgeText, renderBadge would be great, just like in the `react-native-tab-navigator`.

Thoughts?

**Comment by ptomasroos** [comment]
Great idea. Will submit a PR
