### ISSUE TITLE
withNavigation hoc breaks with SlidingTabNavigation

### ISSUE THREAD

**Issue by chirag04** [exponentjs/ex-navigation#111]
I'm going to debug this in some time.

cc @brentvatne @skevy

**Comment by dodomasta** [comment]
Hi @chirag04 , did you manage to around this issue ?

**Comment by chirag04** [comment]
No. I couldn't find time to debug this.

**Comment by satya164** [comment]
Hey @chirag04! What exactly breaks?

**Comment by chirag04** [comment]
If i remember correctly using `withNavigation` on a component inside your screen was breaking.

something like this:

```js

// slidingTab navigation setup here.
SomeScreen = () => <SomeComponent />
SomeScreen.route = { ... };

SomeComponent = () => <View><Compo1 /><Compo2 />;

Compo2 = () => <View />
export default withNavigation(Compo2);
```

**Comment by chirag04** [comment]
duplicate https://github.com/exponentjs/ex-navigation/issues/111
