### ISSUE TITLE
StackNavigation unable to animate on push and pop

### ISSUE THREAD

**Issue by anupkale1984** [exponentjs/ex-navigation#125]
Unable to add push and pop animation in StackNavigation:
Tried following 
`<StackNavigation
    defaultRouteConfig={{
        navigationBar: {
            backgroundColor: Colors.appThemeColor,
            tintColor: 'whitesmoke',
        }
    }}
    configScene={ExNavigator.SceneConfigs.FloatFromRight}
    initialRoute={Router.getRoute('locator')} />`

Please, let me know if i am missing anything here.

**Comment by anupkale1984** [comment]
Thanks brent. Resolved with following
`import { NavigationStyles } from '@exponent/ex-navigation';

class Whatever extends React.Component {
  static route = {
     styles: NavigationStyles.FloatVertical,
  }
}`

**Comment by pyankoff** [comment]
Thank you @anupkale1984 :) I spent some time looking for a way to implement modal with vertical animation.
