### ISSUE TITLE
updateCurrentRouteParams interferes with transition rendering

### ISSUE THREAD

**Issue by michaelswe** [exponentjs/ex-navigation#132]
I'm trying to set my title with updateCurrentRouteParams, but it won't work without a timeout. The example code from the docs work:

    componentDidMount() {
      setTimeout(() => {
        this.props.navigator.updateCurrentRouteParams({
          projectName: this.props.project.get('name')
        })
      }, 1000);
    }

But the same code without timeout interferes with the view transition and the final view is not rendered:

    componentDidMount() {
      this.props.navigator.updateCurrentRouteParams({
        projectName: this.props.project.get('name')
      })
    }

If I back down the timeout gradually I can see that the transition halts half ways. Am I using this function in a bad way?

This seems to be the fastest way to change the title without getting into problems:

    InteractionManager.runAfterInteractions(() => {
      this.props.navigator.updateCurrentRouteParams({
        projectName: this.props.project.get('name')
      })
    });

Is there no way to get hold of the props before the view transition starts? I'd like to have my title in place from start, i.e. not with a visible delay. 

I'm only sending an id to the view and let mapStateToProps find the project. It would feel awkward if I had to lookup the project name before mapStateToProps just to write the project name in the title.

**Comment by chirag04** [comment]
duplicate of https://github.com/exponentjs/ex-navigation/issues/32

cc @skevy @janicduplessis

**Comment by michaelswe** [comment]
Thanks @chirag04 . I did a search before posting, but apparently I failed. Closing this one.
