### ISSUE TITLE
Unexpected token at ExNavigation.js

### ISSUE THREAD

**Issue by anupkale1984** [exponentjs/ex-navigation#153]
Unexpected token at ExNavigation.js at 31:9
Configured as a fresh application, followed all steps except exponent changes. Using React-Native plain application.
Can't we use it with react-native?

**Comment by rogchap** [comment]
Have you configured `babel-preset-react-native-stage-0` correctly?

**Comment by anupkale1984** [comment]
Yes, i configured it correctly. 
I was able to resolve it with. Development server restart as mention on this post
[https://www.npmjs.com/package/babel-preset-react-native-stage-0](url)

**Comment by parijatsahai** [comment]
@anupkale1984 Could you please explain what exactly did you do for "Development server restart"?  The step to reset cache in the link you provided isn't working for me.
