### ISSUE TITLE
Updating route params not working

### ISSUE THREAD

**Issue by laclance** [exponentjs/ex-navigation#155]
I am trying to change route params as per the docs but the title is not updating.
  
static route = {
    navigationBar: {
     title(params) {return params.title},
   },
 };

 componentsDidMount(){
   setTimeout(() => {
   this.props.navigator.updateCurrentRouteParams({
       title: 'newTitle'
   })}, 1000);
 }

**Comment by chirag04** [comment]
duplicate of https://github.com/exponentjs/ex-navigation/issues/32.

cc @skevy @brentvatne

**Comment by laclance** [comment]
Thank you, sorry didn't search thoroughly enough for a duplicate.
