### ISSUE TITLE
Navigating back quickly on iOS breaks app

### ISSUE THREAD

**Issue by glenchao** [exponentjs/ex-navigation#159]
![simulator screen shot oct 12 2016 9 43 58 am](https://cloud.githubusercontent.com/assets/2184589/19314569/a1372224-9068-11e6-928d-c0b5aa61e086.png)

I followed the tutorial on this repo and found that if i navigate into a page and quickly navigate back, the app will break as shown above.

**Comment by chirag04** [comment]
cc @janicduplessis

**Comment by satya164** [comment]
Saw this on Android too.

**Comment by ptomasroos** [comment]
This always happens if you for example do 

```
    this.props.navigation.performAction(({ tabs, stacks }) => {
      tabs('main').jumpToTab('messages');
      stacks('messages').push(AppRouter.getRoute('myroute'));
    });
```

Remove one or the other it works fine. Aka in this case it should probably not start doing the transition before entire lambda has run.
