### ISSUE TITLE
Unable to resolve module @exponent/ex-navigation

### ISSUE THREAD

**Issue by juanbar** [exponentjs/ex-navigation#164]
Unable to resolve module @exponent/ex-navigation from /Users/juan/Desktop/myapp/MyApp/app/containers/MyApp.js: Unable to find this module in its module map or any of the node_modules directories under /Users/node_modules/@exponent/ex-navigation and its parent directories

I tried the following, but it does not work:

1. Clear watchman watches: `watchman watch-del-all`.
2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
3. Reset packager cache: `rm -fr $TMPDIR/react-*` or `npm start -- --reset-cache`.

npm --version
3.10.8

react-native --version
react-native-cli: 1.0.0
react-native: 0.34.0

**Comment by cyprusglobe** [comment]
@juanbar how are you importing? ```@exponent/ex-navigation```

**Comment by juanbar** [comment]
Solved by reinstalling module. Thanks!

**Comment by khanghoang** [comment]
@juanbar can you close this issue then? Thanks :)
