### ISSUE TITLE
Problem with renderLeft on Android

### ISSUE THREAD

**Issue by AgtLucas** [exponentjs/ex-navigation#166]
Hi all!

Let's say that I have something like this:

```javascript
navigationBar: {
 renderLeft: () => <View />,
 renderTitle: (route) => <View><Text>My Header!</Text></View>,
 backgroundColor: '#08C'
}
```

I'm passing an empty `<View />` to the `renderLeft` property because I wanna hide the back arrow.

On iOS works fine, but when I try on Android, the back arrow's area still there:

Without the empty `<View />`.
![screen shot 2016-10-14 at 10 11 06 am](https://cloud.githubusercontent.com/assets/1909761/19388570/b03b4018-91f6-11e6-8c21-b73087e37b05.png)

With the empty `<View />`
![screen shot 2016-10-14 at 10 11 52 am](https://cloud.githubusercontent.com/assets/1909761/19388576/b4fde984-91f6-11e6-89a4-7298fcf3a0d0.png)

See?

Any ideas?

Thanks!

**Comment by chirag04** [comment]
try `renderLeft: () => null`

**Comment by AgtLucas** [comment]
@chirag04 Sorry, I forgot to mention that I already tried that. No joy. :/ With `null` I can't even hide the arrow.

**Comment by chirag04** [comment]
that looks like a bug. Can you debug what's adding that space.

look for `renderLeft` in exNavigationStack and `_renderSubView` in exNavigationBar

**Comment by AgtLucas** [comment]
@chirag04 Sure, how can I do that on Android? (I'm using Genymotion).

**Comment by AgtLucas** [comment]
@chirag04 Not sure if I'm right, but I toggled the inspector on simulator menu, I didn't see any `renderLeft` or `_renderSubView` when I tapped in that area.

**Comment by cyprusglobe** [comment]
i think i found the bug maybe

here is a workaround

https://github.com/exponentjs/ex-navigation/blob/4b5915752e82a8af9601eb8e167f88b7f61299d0/src/ExNavigationStack.js#L546-L548

switch this 

```
if (maybeLeftComponent) {
  return maybeLeftComponent;
}
```
with this
```
if (maybeLeftComponent) {
  return maybeLeftComponent;
} else {
  return null
}
```

then using

```
  static route = {
    navigationBar: {
      title: 'Example Page Name',
      renderLeft: () => null,
    },
  };

**Comment by AgtLucas** [comment]
@cyprusglobe Nice, this works!

PR maybe?

**Comment by cyprusglobe** [comment]
@AgtLucas i can create one if you would like me too

/cc @brentvatne @satya164 @skevy

**Comment by AgtLucas** [comment]
@cyprusglobe If you don't mind... I can do that too! :)

**Comment by cyprusglobe** [comment]
Alright PR inbound, any suggestion on a title? haha

**Comment by AgtLucas** [comment]
@cyprusglobe No idea! XD

Don't forget to do the same with `maybeRight`. :)

**Comment by cyprusglobe** [comment]
@AgtLucas Already on it 👍
