### ISSUE TITLE
Recommended way to add props to components served by router?

### ISSUE THREAD

**Issue by cmrichards** [exponentjs/ex-navigation#170]
In the example below I have a database variable (a couchdb database connection) that I'd like to pass as props to the components served by the router.  What's the recommended way of doing this in ex-navigation?   I've looked at the available props on NavigationProvider and can't see any easy way. I'm sure I'm missing something obvious here...

btw, thanks for the great library!

```
import {
  createRouter,
  NavigationProvider,
  StackNavigation,
} from '@exponent/ex-navigation'

const Router = createRouter(() => ({
  jobs: () => Jobs,
  sample: () => Sample
}))

render () {
  const database = this.openDatabase()
  <NavigationProvider router={Router}>
        <StackNavigation initialRoute={Router.getRoute('jobs')} />
  </NavigationProvider>
}

```

I asked this question on stackoverflow with no luck : http://stackoverflow.com/questions/40009877/exnavigation-how-to-pass-props-to-all-router-components

**Comment by jozan** [comment]
This is now answered in [StackOverflow](https://stackoverflow.com/questions/40009877/exnavigation-how-to-pass-props-to-all-router-components/40062944#40062944).
