### ISSUE TITLE
[babel] How to use react-native-stage-0/decorator-support with Relay.

### ISSUE THREAD

**Issue by joonhocho** [exponentjs/ex-navigation#173]
Cross posting: https://github.com/facebook/relay/issues/1416

**Comment by chirag04** [comment]
answered on relay repo. Please close the ticket if it all works fine. make sure you clear the packager cache.

**Comment by joonhocho** [comment]
Thank you @chirag04! Closing the issue since your solution worked for me!
Thanks! It worked for me.
I removed extra parenthesis for relay plugin, too.
Here's my final babelrc that works:
```
{
      "presets": [
        "react-native-stage-0/decorator-support"
      ],
      "plugins": [
        "./plugins/babelRelayPlugin"
      ]
    }
```

**Comment by sibelius** [comment]
working version with Relay and Ex-Navigation - https://github.com/sibelius/ExNavRelay
