### ISSUE TITLE
How to use ex-navigation with Relay?

### ISSUE THREAD

**Issue by lucasbento** [exponentjs/ex-navigation#175]
Is there any guide or something like 
https://github.com/r0b1n/rnrf-relay-renderer?

**Comment by chirag04** [comment]
Just had a quick glance through the source of that lib. It's more of less like this gist from @janicduplessis : https://gist.github.com/janicduplessis/f513032eb37cdde5d050d9ce8cf0b92a

That gist should work for most cases.

**Comment by rturk** [comment]
Hi @chirag04 can you share your thoughts regarding Ex-Navigation with Relay? We currently use RNRF lib (listed above) and are seriously considering Ex-navigation as new navigation engine, however it's not clear if will support Relay.

**Comment by chirag04** [comment]
We migrated our app from ex-navigator to ex-navigation, using relay with both the libs. Relay per se is not tied to any navigation lib.  That gist i posted above has nothing to do with ex-navigation or any navigation lib.

You should be fine in terms of relay support with ex-navigation.

**Comment by lucasbento** [comment]
@chirag04: thank you for sharing that gist, really hepful!

It would be nice to see an ex-navigation example with that gist though.

I'll try to send a PR when I have some time.

Thank you guys!

**Comment by sibelius** [comment]
working version with Relay and Ex-Navigation - https://github.com/sibelius/ExNavRelay
