### ISSUE TITLE
Expose renderNavigationView on DrawerNavigation

### ISSUE THREAD

**Issue by sibelius** [exponentjs/ex-navigation#181]
`DrawerNavigation` uses `DrawerLayout` under the hood to create the `Drawer`

I've tried to create a custom View that has a ListView inside Drawer using `renderHeader`, but it does not scroll well

I think that exposing `renderNavigationView` method on `DrawerNavigation` can help on this case and other custom views inside Drawer

**Comment by JonasJonny** [comment]
Exactly what I was looking for. Thanks.

**Comment by JonasJonny** [comment]
Exactly what I was looking for. Thanks.

But how is it possible to pass DrawerNavigationItem's into custom renderNavigationView component for `{this._renderDrawerItems()}`?

**Comment by sibelius** [comment]
hmm, this is not possible yet on my PR (https://github.com/exponentjs/ex-navigation/pull/182)

but u can easily pass this props to it, I can add it 

@skevy do u think this PR (https://github.com/exponentjs/ex-navigation/pull/182) could get in master?

**Comment by skevy** [comment]
Merged!

**Comment by sibelius** [comment]
@JonasJonny if u wanna this https://github.com/exponentjs/ex-navigation/issues/181#issuecomment-256645456, could u send a PR?

u just need to change this file https://github.com/exponentjs/ex-navigation/blob/a434bd479cc30a3dd7048e5ce5e72c2a2be6f227/src/drawer/ExNavigationDrawerLayout.js#L45 I guess

**Comment by annelorraineuy** [comment]
I'm stuck with how to pass the `DrawerNavigationItem`s into the custom `renderNavigationView` component / [#181](https://github.com/exponent/ex-navigation/issues/181#issuecomment-256645456) . Would anyone care to explain how this could be done?

**Comment by sibelius** [comment]
@annelorraineuy it is not possible to pass `DrawerNavigationItem`s into `renderNavigationView` yet

we need another PR to address this

**Comment by annelorraineuy** [comment]
Thanks for replying so quickly @sibelius. Do you know a work-around to make let's say Listview menu items inside the custom `renderNavigationView` work? If I make the menu items get the master stack and just push the routes from that.. Will that work according to how this is built?
