### ISSUE TITLE
[iOS] Disable slide to back gesture on certain screen

### ISSUE THREAD

**Issue by khanghoang** [exponentjs/ex-navigation#189]
Hi guys, I went into the issue when I wanted to disable slide to back gesture on certain screens. In React Native ExpirimentalNavigation, it has `enableGestures` prop to enable/disable that feature. FYI https://github.com/facebook/react-native/issues/10440

I checked ex-navigation code and i couldn't find how I can do it 😭

**Comment by sibelius** [comment]
Please read this gist https://gist.github.com/knowbody/ce483742a1761658b767428a0ed35147#file-ex-navigation-md

U can do 

static route = {
   gesture: null,
}

**Comment by khanghoang** [comment]
@sibelius  thanks, it works 🎉
