### ISSUE TITLE
(Question) transition animation configuration

### ISSUE THREAD

**Issue by ivpusic** [exponentjs/ex-navigation#202]
is it possible to turn off default animation when doing scene push? Right now I get this from right to left animation, but in some cases I would like to turn off this.

**Comment by sibelius** [comment]
Take a look on this gist https://gist.github.com/knowbody/ce483742a1761658b767428a0ed35147#file-ex-navigation-md

U have styles that u can configure how transition works

**Comment by ivpusic** [comment]
Thanks a lot
