### ISSUE TITLE
Jest failed

### ISSUE THREAD

**Issue by magrinj** [exponentjs/ex-navigation#204]
Hi guys,

I got some problem with `jest` and `ex-navigation`, I write some snapshot test, and when I run `npm test` I got this error:

```
 FAIL  src/screens/auth/__tests__/AuthScreen-test.js
  ● Test suite failed to run

    /Users/magrin_j/BeJoe/bejoe-mobile-v2/node_modules/@exponent/ex-navigation/src/ExNavigation.js:5
    export { default as NavigationProvider } from './ExNavigationProvider';
    ^^^^^^
    SyntaxError: Unexpected token export

      at transformAndBuildScript (node_modules/jest-runtime/build/transform.js:305:10)
      at Object.<anonymous> (src/navigation/Router.js:1:165)
      at Object.<anonymous> (src/screens/auth/AuthScreen.js:15:13)
```

**Comment by brentvatne** [comment]
See this part of the jest docs: https://facebook.github.io/jest/docs/tutorial-react-native.html#preprocessorignorepatterns-customization

This works out of the box with the jest-exponent preset: https://github.com/exponentjs/jest-exponent/blob/master/jest-preset.json#L21-L23

**Comment by sibelius** [comment]
@magrinj u can add @exponent/ex-navigation to `preprocessorIgnorePatterns` of ur jest config

```jsx
"jest": {
    "preset": "jest-react-native",
    "preprocessorIgnorePatterns": [
      "node_modules/(?@exponent/ex-navigation|@exponent/react-native-touchable-native-feedback-safe)"
    ],
    "verbose": true,
    "moduleFileExtensions": [
      "js",
      "json",
      "es6",
      "ios.js"
    ]
  },
```

**Comment by magrinj** [comment]
@brentvatne & @sibelius Thanks for your answers, @brentvatne in fact the `jest-exponent` is not working out of the box with `react-native@0.36` because of this: https://github.com/facebook/jest/pull/1989

So, I use `jest@test` and `jest-react-native@test` :/ 

With your solution @sibelius I got the following error when I run `npm test`: 

```
Error: Jest: `preprocessorIgnorePatterns` and `transformIgnorePatterns` cannot be used together. Please change your configuration to only use `transformIgnorePatterns`.
```

**Comment by magrinj** [comment]
Ok, seems I solve it with this configuration of jest:

```
  "jest": {
    "preset": "jest-react-native",
    "transformIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-clone-referenced-element|exponent|@exponent/*)"
    ]
  },
```
