### ISSUE TITLE
StackNavigation transition Android

### ISSUE THREAD

**Issue by theobouwman** [exponentjs/ex-navigation#206]
The StackNavigation transition on iOS is the default one (slides in form the right).
But on Android there is no transition, it just pops in.

`<StackNavigation
    id="root"
    defaultRouteConfig={{
        navigationBar: {
            backgroundColor: '#fff',
            tintColor: '#000',
            },
        }}
    initialRoute={Router.getRoute('home')}
/>`

Do I need to set a prop?

If someone could help, he would we a hero to me.

**Comment by sibelius** [comment]
follow this gist https://gist.github.com/knowbody/ce483742a1761658b767428a0ed35147#how-can-i-slide-my-view-from-bottom-up-transition-from-one-screen-to-the-other

**Comment by theobouwman** [comment]
@sibelius thanks a lot. But on android the transitions are pretty slow. Like 10 fps.
How is this?

**Comment by sibelius** [comment]
transitions are slow when debugger is `on` on Android

**Comment by theobouwman** [comment]
@sibelius  thanks, didn't knew that

**Comment by sibelius** [comment]
@theobouwman can u close this?

**Comment by theobouwman** [comment]
The transitions when testing on android are still pretty slow. How is this?

**Comment by theobouwman** [comment]
Nvm, when testing the release version it was fixed.
