### ISSUE TITLE
Scroll to top programatically via tab, possible?

### ISSUE THREAD

**Issue by MossP** [exponentjs/ex-navigation#207]
I'd like to be able to click a tab and have it scroll the page to the top (under certain circumstances - tab already visible and at index 0) I have the logic all working and i can console log the scrollToTop at the correct time but can't see how to get access to a reference inside the route to be able to trigger the scroll action. Is there an even to scroll to top or a way of getting access to refs inside a route?

**Comment by sibelius** [comment]
@MossP could u share ur code to make the scroll to top when u click in the tabbar?

we should have a recipe folder like ava-js (https://github.com/avajs/ava/tree/master/docs/recipes) to store all this common logics

**Comment by MossP** [comment]
@sibelius I don't have it fully working yet. Just parts from each side that I need to wire up together. As soon as I get it working I'll post the solution that I went with though.

**Comment by MossP** [comment]
@sibelius OK I found a really hacky way around it (I'm not proud of this).


```
setRef(id, ref){
  listViewRefs[id] = ref;
}
```

```
<TabItem
          id="feed"
          title="Home"
          selectedStyle={styles.selectedTab}
          onPress={(tabItemOnPress, event) => this._onTabPress(tabItemOnPress, event, 'feed')}
          >
          <StackNavigation
            id="feed"
            navigatorUID="feed"
            initialRoute={Router.getRoute('feed', {setRef:this.props.setRef})}
            {...this.props}
          />
        </TabItem>
```

in each initial route I pass the listView ref up to root
```
  componentDidMount(props) {
    // this is not available if the component wasn't passed as the initial route of a tab
    if(this.props.setRef){ 
      this.props.setRef('feed', this.refs._listView);
    }
  }
```

Then use a modified version of JunkSlices reset code to bounce the listView to the top.
```
  _onTabPress(tabItemOnPress: Function, event: Object, tabID): void { // 
    tabItemOnPress();
    var navigation = this.refs.tabNav.context.navigation;
    var _targettedListView = listViewRefs[tabID];
    navigation.performAction(({ tabs, stacks }) => {
      const { currentNavigatorUID } = navigation.navigationState;
      if (navigation.navigationState.currentNavigatorUID !== 'main') {
        if(navigation.navigationState.navigators[tabID].index > 0){
          stacks(tabID).popToTop(tabID);
        }
        else
        {
          // scroll to top.
          if(_targettedListView){
            _targettedListView.scrollTo(0);
          }
        }
      }
    });
  }
```

**Comment by chirag04** [comment]
One way of doing this is to emit a `scoll_to_top` event that your scrollview is listening for. That way you can avoid having to deal with `refs`

**Comment by MossP** [comment]
thanks @chirag04. I hadn't thought of trying it that way.
