### ISSUE TITLE
Navigating from within StackNavigation not possible

### ISSUE THREAD

**Issue by theobouwman** [exponentjs/ex-navigation#212]
I want to navigate when pressing the `renderRight` element. But it is not possible since `this.props.navigator` is undefined

` render() {
        return (
            <StackNavigation
                id="root"
                defaultRouteConfig={{
                    navigationBar: {
                        backgroundColor: '#fff',
                        tintColor: '#000',
                        renderRight: () => {
                            return (
                                <Entypo style={{margin: 10}} onPress={() => this.props.navigator.push(Router.getRoute('listPage'))} name="list" size={32} color="black" />
                            );
                        }
                    },
                    styles: {
                        ...NavigationStyles.SlideHorizontal
                    }
                }}
                initialRoute={Router.getRoute('home')}
            />
        );
    }`

How do I achieve this?

**Comment by sibelius** [comment]
u should use `@withNavigation`

example:
```js
@withNavigation
export default class NavigationBarBackButton extends Component {
  render() {
    const { tintColor } = this.props;

    return (
      <TouchableOpacity
        onPress={this._onPress}
        hitSlop={BACK_BUTTON_HIT_SLOP}
        style={buttonStyles.buttonContainer}
      >
        <Image
          style={[buttonStyles.button, tintColor ? {tintColor} : null]}
          source={require('./ExNavigationAssets').backIcon}
        />
      </TouchableOpacity>
    );
  }

  _onPress = () => this.props.navigator.pop();
}
```

**Comment by theobouwman** [comment]
Your solution does not work. I fixed it with adding an extra stacklayout as main navigator.
