### ISSUE TITLE
How Toggle Drawer from navigatonBar

### ISSUE THREAD

**Issue by haikyuu** [exponentjs/ex-navigation#218]
I need to toggle the drawer from the navigation bar `renderLeft` , i tried 

```javascript
let navigatorUID = store.getState().navigation.currentNavigatorUID;
store.dispatch(NavigationActions.toggleDrawer(navigatorUID))
```

But it doesn't work. Any idea?

**Comment by sibelius** [comment]
use @withNavigation
```jsx
@withNavigation
export default class NavigationBarMenuButton extends Component {
  render() {
    const { tintColor, navigation } = this.props;

    const navigator = navigation.getNavigator('drawer');

    return (
      <TouchableOpacity style={buttonStyles.buttonContainer} onPress={() => navigator.toggleDrawer()}>
        <Image
          style={[buttonStyles.menuButton, tintColor ? { tintColor } : null]}
          source={require('./ExNavigationAssets').menuIcon}
        />
      </TouchableOpacity>
    );
  }
}
```

**Comment by haikyuu** [comment]
Thanks, but i get this error
`Navigator does not exist`

**Comment by haikyuu** [comment]
I found what was causing it. I need to use the id given to the `DrawerNavigation`, in the example of the Readme, it's `main`
`const navigator = navigation.getNavigator('main');`
I'll add it to the readme when i have some time. 
By the way, any plans on writing the docs? I'm willing to help.

**Comment by sibelius** [comment]
@haikyuu feel free to send a PR to improve the docs

**Comment by JulianKingman** [comment]
Ah, OK, a further caveat: there is both a navigatorID and a navigatorUID. The function to get navigator by UID is `getNavigatorByUID('uid goes here')`.

**Comment by sibelius** [comment]
@haikyuu @JulianKingman added this to https://github.com/sibelius/ex-navigation-recipes

**Comment by haikyuu** [comment]
Thanks a lot :)
