### ISSUE TITLE
Pushing new route slow with heavy components.

### ISSUE THREAD

**Issue by theobouwman** [exponentjs/ex-navigation#224]
When pushing a new route to the navigationstack, and when the route is pretty heavy loaded with components (react-native-looped-carousel and AdMob ad) the transition/animation from page to page isn't always smooth.

At first I tested this on the debug mode with live reload. But after that I tested it on the release version of the app.

I think that react-native can't handle heavy component mounts well because of this easy reproducible issue.

And I made an issue on the react-native-looped-carousel repo [#45](https://github.com/appintheair/react-native-looped-carousel/issues/45)

**Comment by sibelius** [comment]
Do u have a repo to reproduce this? Animations r slow if chrome debugger is not in foreground

**Comment by satya164** [comment]
Refer https://facebook.github.io/react-native/docs/performance.html
