### ISSUE TITLE
Use native animations when possible

### ISSUE THREAD

**Issue by haikyuu** [exponentjs/ex-navigation#229]
[The latest version of react-native](https://github.com/facebook/react-native/releases/tag/v0.37.0) has shipped with [native animations when possible](https://github.com/facebook/react-native/commit/f9779e3eb79d50ddf0d80bbc0d047914d9e0c10c) in the navigatorExperimental.
Is it possible to disable gestures in ex-navigation? so that we benefit from native animations.

**Comment by vonovak** [comment]
You probably don't want to disable gestures, because especially ios users are used to those. On Android they are disabled by default afaik.

**Comment by haikyuu** [comment]
Nice, so we'll automatically get the boost in performance in Android.
