### ISSUE TITLE
[bug] 1.5.0 is incompatible with non-exponent projects

### ISSUE THREAD

**Issue by jsierles** [exponentjs/ex-navigation#23]
Just to track the issue mentioned on Slack, this line bombs if you're not including the exponent package in your project:

https://github.com/exponentjs/ex-navigation/blob/master/src/ExNavigationBar.js#L13

**Comment by FaridSafi** [comment]
+1

**Comment by chirag04** [comment]
just to track the workaround we discussed on Slack: I have a fork that temp fixes this: https://github.com/chirag04/ex-navigation/tree/blur-view

**Comment by brentvatne** [comment]
@jsierles @FaridSafi @chirag04 - sorry about that, published 1.5.3 which resolves this issue
