### ISSUE TITLE
DrawerNavigationItem Positioning

### ISSUE THREAD

**Issue by adrianha** [exponentjs/ex-navigation#244]
Hi,
is it possible to make DrawerNavigationItem become on the bottom of drawer.
I've tried using flex styling but still couldnt make it.
Any ideas?
Thank you

**Comment by sibelius** [comment]
you can use `renderNavigationView` https://github.com/exponentjs/ex-navigation/blob/master/src/drawer/ExNavigationDrawer.js#L146

to have full control over DrawerNavigation

**Comment by adrianha** [comment]
oh ok, got it @sibelius , thank you..
