### ISSUE TITLE
Exposing withNavigation as a component

### ISSUE THREAD

**Issue by sonaye** [exponentjs/ex-navigation#249]
This is a proposal (or a request for a feature) to extend the withNavigation API to be used as a top level component. One common use case of withNavigation is to provide stateless components with access to the navigator property, the component itself is still stateless and only needs that property exposed.

The current workaround is to convert the stateless component to statefull even though no state is present nor any life cycle methods are used. This happens because withNavigation requires the component it is wrapping to inherent all of React.Component goodies.

e.g. let's say that we have a simple stateless component

```javascript
const Stateless = () => (
  <TouchableOpacity onPress={/* no props.navigator */} />
);
```

and we wish to provide it with access to the navigator API so that we can push or pop a route for example, we would have to reimplement the component above to something like this

```javascript
@withNavigation class Stateless extends Component {
  render() {
    return (
      <TouchableOpacity onPress={/* has access to this.props.navigator */} />
    );
  }
}
```

This is too much for adding such a simple common method. Exposing withNavigation as a component would allow for something like this

```javascript
const Stateless = ({ navigator }) => (
  <WithNavigation>
    <TouchableOpacity onPress={/* has access to navigator */} />
  </WithNavigation>
);
```

Extending the functionality of the stateless component can be done now without having to convert it to a class that inherits all of the React unnecessary add ons. Furthermore, using decorators would becomes a matter of choice now and not a requirement.

**Comment by cyprusglobe** [comment]
cc @skevy @brentvatne

**Comment by satya164** [comment]
> This happens because withNavigation requires the component it is wrapping to inherent all of React.Component goodies

Where'd you get that? I did a quick scan of the code and didn't find anything obvious.

> This is too much for adding such a simple common method. Exposing withNavigation as a component would allow for something like this

No, it doesn't work that way. You're using `withNavigation` inside the component, so it can't pass the props to itself.

> Furthermore, using decorators would becomes a matter of choice now and not a requirement.

You don't have to use decorators,

```
export default withNavigation(MyComponent)
```

**Comment by sonaye** [comment]
`@withNavigation class MyClass {}` throws an error, withNavigation requires the component it is applied on to have React.Component as a parent `@withNavigation class MyClass extends React.Component {}`.

> No, it doesn't work that way. You're using withNavigation inside the component, so it can't pass the props to itself.

`<WithNavigation>` -with a capital W- should pass the navigator prop to its children, it would have a slightly different behaviour, this is my point.

And it is true that decorators are not are not a requirement, my bad on this one.

**Comment by satya164** [comment]
> `@withNavigation class MyClass {}` throws an error

Of course you have to use a React component as a child, but it could be a class component or stateless component, so doesn't have to inherit anything. Why would you use a plain class here?

> `<WithNavigation>` -with a capital W- should pass the navigator prop to its children, it would have a slightly different behaviour, this is my point.

In your example, the `onPress` of `TouchableOpacity` won't have access to the navigator prop. In the function argument of the component you're destructuring the `navigator` prop, but the component is not the child component of `WithNavigation`.

But anyways, stateless components work fine with `withNavigation`

**Comment by sonaye** [comment]
You are right, maybe the description of what I am trying to achieve wasn't on point.

From my experience, withNavigation fails when it comes to stateless components that are **not declared in createRouter** which is rarely the case, I remember clearly in one of the cases I faced an error being thrown and its fix was to switch to a stateful implementation, I have no code to showcase here because that error has been fixed now and the non working code is obsolete.

I went through my code and switched a couple of components to their original stateless structure, thanks to createRouter which by default gives any declared route access to the navigator prop (this wasn't on my mind when I opened this issue). This is sufficient for me at the moment and solved the problem that made me suggest exposing WithNavigation as a parent component in the first place.

I still think that enhancing the withNavigation API by exposing a new WithNavigation component would make a nice addition.

**Comment by satya164** [comment]
> From my experience, withNavigation fails when it comes to stateless components that are not declared in createRouter which is rarely the case

Hmm... non-route stateless components work fine with `withNavigation`. If you have a repro case where it doesn't work, then please link to it.

> I still think that enhancing the withNavigation API by exposing a new WithNavigation component would make a nice addition.

When you have it as a component it always requires you to create another component so that you could wrap the child one. Why would you want that though?

**Comment by sonaye** [comment]
I don't unfortunately, this was a while ago. If I do I will come back and reference it here.

>Why would you want that though?

A more declarative and cleaner syntax. Same as

`<NavigationProvider {...{ router, children: <App /> }} />`

although you could argue that no props are passed to withNavigation. This is not a necessary addition, but an enhancement to the API in my opinion. The whole idea came from [here](https://github.com/mobxjs/mobx-react/issues/138).

**Comment by satya164** [comment]
@sonaye 

> A more declarative and cleaner syntax

I don't think it's clearer. You have to create an entirely new component to use it. Also here the parent needs to know whether the child component needs the `navigation` prop, which leads to coupling.

If you try to use such a component you'll understand what I'm trying to explain.
