### ISSUE TITLE
crash on Android at app launch

### ISSUE THREAD

**Issue by ajonno** [exponentjs/ex-navigation#253]
hi all, firstly great job with this api, like it a lot and want to use in our ios/droid app launching Q1.

just starting with a toy app to get a feel for the api. ios was fine. however we got a crash on app launch for Android - ".../ExNavigation.js: Method has decorators, put the decorator plugin before the classes one...at ExNavigationStack.js:129:2"

our .babelrc is this:
```
{
    "presets": [
        "react-native-stage-0/decorator-support",
        "react-native"
    ],
    "plugins": [
        "transform-decorators-legacy"
    ]
}

```

We tried removing the "react-native" entry, tried changing the order etc. nothing fixed the crash.

Package.json dependencies are:
```
"dependencies": {
    "@exponent/ex-navigation": "^2.1.0",
    "babel-preset-react-native-stage-0": "^1.0.1",
    "react": "15.3.2",
    "react-native": "0.37.0"
  },
"jest": {
    "preset": "jest-react-native"
  },
  "devDependencies": {
    "babel-jest": "17.0.2",
    "babel-preset-react-native": "1.9.0",
    "jest": "17.0.2",
    "jest-react-native": "17.0.2",
    "react-test-renderer": "15.3.2"
  }
```

Appreciate your help to resolve this.

cheers
Angus

**Comment by brentvatne** [comment]
Hello! All you need is this:

```
{
    "presets": [
        "react-native-stage-0/decorator-support",
    ],
}
```

**Comment by ajonno** [comment]
hey, thanks for super speedy reply! im sure i tried that but here goes.....

**Comment by ajonno** [comment]
oky dokey - that worked fine ! but i had definitely tried that too.  i dont know if this may have made a diff but i actually deleted my node_modules dir and did a fresh npm install, then re-ran.

anyways all good now, thanks !!

**Comment by brentvatne** [comment]
glad it fixed it!
