### ISSUE TITLE
Missing .babelrc ?

### ISSUE THREAD

**Issue by ahanriat** [exponentjs/ex-navigation#26]
**Issue**:
When running the example, I got an error due to missing babel configuration
![screen shot 2016-08-10 at 11 45 41](https://cloud.githubusercontent.com/assets/1374161/17550964/e6ff6cbe-5ef7-11e6-9aac-3c5fd3318443.png)

@ide give me the solution, creating a `.babelrc` with this conf:
```
{
  "presets": ["react-native-stage-0/decorator-support"]
}
```
And then run `npm install -D babel-preset-react-native-stage-0` to get the preset

**Comment by brentvatne** [comment]
good point @ahanriat - we recently switched away from shipping the transpiled code to instead shipping the raw source, which means that you'll need to have the same transforms available as are used by ex-navigation.

Added this to the docs in https://github.com/exponentjs/ex-navigation/commit/6d680ba4d05cfc82c3c090d909833a100dd66241

**Comment by ahanriat** [comment]
Thanks @brentvatne  !
