### ISSUE TITLE
remove/hide the bottom border of the nav bar 

### ISSUE THREAD

**Issue by ajonno** [exponentjs/ex-navigation#264]
hi guys, is it possible (via a prop?) to remove the "underline"/bottom border of the nav bar ? 

I need to display a custom left back button but effectively 'hide' the rest of the nav bar (ios & droid). Appreciate it if you can give me some pointers on this. I've attached an image so you can see what i mean. Thanks!

![image](https://cloud.githubusercontent.com/assets/3005269/20448629/2a782d10-ae39-11e6-9f96-f3ec738cea59.png)

**Comment by brentvatne** [comment]
hello! you should just make the navbar invisible with `visible: false` and then add the back button manually to your view

**Comment by ajonno** [comment]
thanks Brent! sorry to be dose but when you say 'add manually' what did you mean ?

**Comment by ajonno** [comment]
forest for the trees! thanks a lot Brent :-)
