### ISSUE TITLE
routing to a new view via actions 

### ISSUE THREAD

**Issue by ajonno** [exponentjs/ex-navigation#290]
is it possible to trigger a route directly from within an action creator ? i saw the code snippets in your README for this but it still isnt quite clear to me how to implement.

im using redux-thunk for login flow which is working nicely in and of itself. however when that login promise resolves OK - i then want to trigger a route to the home view.

here's code snippet:
```
      dispatch({ type: LOGIN_USER_START });
      
      firestack.auth.signInWithEmail(email, password)
      .then((user) => {
         dispatch({ type: LOGIN_USER_SUCCESS, payload: user });
         //*** ID LIKE TO TRIGGER THE ROUTE TO HOME VIEW RIGHT HERE *****
      })
      .catch((error) => {
         loginUserFailed(dispatch, error.description);
      });
```

what import's do i need to make that route succeed, and how can i get a handle on the destination view etc ? thanks for help with this.

**Comment by ajonno** [comment]
its cool i figured it out. lovin' your work here folks!

**Comment by gualcm** [comment]
How did you achieve it? I'm running into the same problem

**Comment by mitajunior** [comment]
How did you achieve this

**Comment by ajonno** [comment]
at top of file (assuming an action creator) make sure you have these imports:
```
...
import Router from '../routing/Router';          //ie. wherever you have defined your routes
import Store from '../state/Store';                  //ie. wherever you have defined your store
import { NavigationActions } from '@exponent/ex-navigation';
...
```

then, whenever you want to navigate the format is like this (ie works ok for me). this example is for a "push" navigation, to the view that maps/corresponds to the route "addToGroup".
```
const navigatorUID = Store.getState().navigation.currentNavigatorUID;
Store.dispatch(
	NavigationActions.push(
		navigatorUID,
		Router.getRoute("addToGroup")
	)
);
```
