### ISSUE TITLE
how to display nav bar on a given tab ?

### ISSUE THREAD

**Issue by ajonno** [exponentjs/ex-navigation#296]
hey all,
we're using ex-Nav as part of our in-dev React Native app. Quick question as we're getting used to the (nice) api 👍 

how can we display a nav bar on a 'standalone' tab. all i mean by that is when user taps on the tab, we'd like to use the ex-Nav nav bar - but the user wont actually be navigating to a different view from here. we know there's a few ways to do this but are keen to use ex-Navigator's nav bar.

![image](https://cloud.githubusercontent.com/assets/3005269/21032740/a255b106-bdff-11e6-8702-e95c3a709177.png)

just to note, in this component we have:

```
import { withNavigation } from '@exponent/ex-navigation';
...

@withNavigation
class ProfileView extends Component {
.....
    static route = {
      navigationBar: {
         visible: true,
         renderBackground: () => <NavBackgroundImage />
      }
     }

....
```

and lastly, we are using Redux and so have ex-navigation wired up like so via root/App.js:

```
....
const navigationContext = new NavigationContext({
      router: Router,
      store: Store
 });

export default class AppNameIsHere extends Component {
...

return (
         <Provider store={Store}>
            <NavigationProvider context={navigationContext}>
               <StackNavigation initialRoute={Router.getRoute('landingPage')} />
            </NavigationProvider>
         </Provider>
);
...
```

**Comment by ajonno** [comment]
played around with the examples and figured it out, thanks

**Comment by lprhodes** [comment]
Can you please provide an example after you figured it out?
