### ISSUE TITLE
On Android useNativeDriver causes red screen

### ISSUE THREAD

**Issue by ptomasroos** [exponentjs/ex-navigation#3]
Native animation offloading is enabled in the Animation of Navigation.
Do we need to add a NativeModule in the MainActivity in order to make this work?

HT: Until its fixed you can disable offloading by setting useNativeDriver: false in ExNavigationStyles.js and it will run just fine on javascript thread instead.

**Comment by skevy** [comment]
Thanks for reporting this @ptomasroos.

This has worked for us because we have more support in our react-native fork for native animations than currently exists in RN OSS. I'm going to turn off `useNativeDriver` in ex-nav until native animation support is more fleshed out (hopefully soon!).

**Comment by skevy** [comment]
Fixed in 7b183678da104a68a936b4cf04f98b3e758815ba.
