### ISSUE TITLE
Replace stack

### ISSUE THREAD

**Issue by Froelund** [exponentjs/ex-navigation#30]
Hi,

Thank you for this great module!

I currently face a challenge. I want to replace the previous stack-entry programmatically.

```
        ---routeB---\
      /               > routeC
---routeA-----------/
```
The user can take multiple "paths" to routeC.
Let's say the user navigates as follows: routeA -> routeB -> routeC.
In routeC he behaves in such a way, that when he presses back, he should return to routeA. So he's stack looks like this: routeA -> routeC.

I've tried using `immediatelyResetStack`, but so far no luck.
```
this.props.navigator.immediatelyResetStack([
    Router.getRoute('routeA'), Router.getRoute('routeC', {routeCSpecificProp: this.props.routeCSpecificProp}))
]);
```

**Comment by Froelund** [comment]
Nevermind - I figured it out.
I was actually on the right path ( Or route :) ).
`immediatelyResetStack` takes a second parameter `index`. This defines where on the new stack, you would like to end up.
So the code would be:
```
this.props.navigator.immediatelyResetStack([
    Router.getRoute('routeA'), Router.getRoute('routeC', {routeCSpecificProp: this.props.routeCSpecificProp}))
], 1); // Notice the 1
```

**Comment by Froelund** [comment]
Just to clarify if someone stumbles upon this issue. Instead of creating a new stack, you should reuse the one that are already made.
```
      var stackOfRoutes = this.props.navigator._getNavigatorState().routes;
      var newRoutesStack = [stackOfRoutes[0], stackOfRoutes[2]];
      this.props.navigator.immediatelyResetStack(newRoutesStack, 1);
```

**Comment by nadirHomeFriend** [comment]
@Froelund great solution , thanks a lot
