### ISSUE TITLE
Cannot update navigationBar backgroundColor via updateCurrentRouteParams()

### ISSUE THREAD

**Issue by joncursi** [exponentjs/ex-navigation#33]
The background color for my scenes are determined based on data (i.e. themed based on user preferences). I would like to use `updateCurrentRouteParams` to update the backgroundColor once the color code has been fetched, however the below throws a warning:

```
  static route = {
    navigationBar: {
      backgroundColor(params) {
        return params.color;
      },
    },
  }
```

<img width="373" alt="screen shot 2016-08-16 at 3 24 34 am" src="https://cloud.githubusercontent.com/assets/4974609/17691172/fe0f9dee-6360-11e6-97f8-e12723b162e2.png">

**Comment by chirag04** [comment]
backgroundColors on navbar supports string and not function unlike title: https://github.com/exponentjs/ex-navigation/blob/master/src/ExNavigationTypeDefinition.js.flow#L39

Feel free to PR. cc @brentvatne @skevy

**Comment by joncursi** [comment]
I also have this same issue for renderRight() and renderLeft(). These params are generated based on prop data, and it appears that they cannot be set within `updateCurrentRouteParams`.
