### ISSUE TITLE
Usage outside of exponent

### ISSUE THREAD

**Issue by pstockley** [exponentjs/ex-navigation#41]
Is it possible to use ex-navigation without using exponent? I really like the look of the API and want to use it within an existing react native app.

**Comment by chirag04** [comment]
yes you can use ex-navigation without using exponent.

**Comment by chirag04** [comment]
feel free to close this issue. There is also an exponent slack channel where you can ask questions like this and get help.

**Comment by pstockley** [comment]
Thanks. The reason I asked is that I saw the example depended on your fork of react native and I wondered if there was any dependency in the navigation code. I will check out the slack channel.
