### ISSUE TITLE
Replace NavigationAnimatedView with NavigationTransitioner

### ISSUE THREAD

**Issue by ptomasroos** [exponentjs/ex-navigation#5]
We should upgrade the library to NavigationTransitioner instead since NavigationAnimatedView is being faded out in RN https://github.com/facebook/react-native/commit/7db7f78dc7d2b85843707f75565bcfcb538e8e51

**Comment by skevy** [comment]
Yep! Aware of this change. We will update it soon.

**Comment by brentvatne** [comment]
@ptomasroos - sorry we haven't got around to this yet, it's definitely still on the radar

**Comment by ptomasroos** [comment]
I can imaging.

No worries. 

At least stuff is getting more stable in fb releases. I think 0.31 or 0.32 is something to vendor. IMHO

**Comment by chirag04** [comment]
@ptomasroos feel free to close this as v1.4 now uses NavigationTransitioner

**Comment by ptomasroos** [comment]
Thanks. Great news!
