### ISSUE TITLE
make showLocalAlert customizable

### ISSUE THREAD

**Issue by chirag04** [exponentjs/ex-navigation#53]
Right now showLocalAlert takes a message and styles to apply. but it still controls the timeout. There is not way to have a dismiss button.

how about an API like:

```js
this.props.navigator.showLocalAlert({
   renderAlert: () => <AlertComponent />,
   timeout: 500, // if not time them alert won't auto close.
});
```

idk if its worth supporting any default with local alerts because most apps would have their own styles and timeouts

cc @skevy @brentvatne

**Comment by brentvatne** [comment]
Yup we can definitely add this kind of stuff. I think there are a lot of apps that don't care about styling this upfront but might want to later on, so it's good to have that fallback. I just implemented this based off of one use case and look forward to people with other use cases submitting PRs to improve it :>

**Comment by chirag04** [comment]
Ok. I'm convinced that we should not modify the `showLocalAlert` api. `message` and `options` is all you need to create an alertBar.

For custom behaviors, we need to let users provide their own alertBar component.

@brentvatne @skevy thoughts?

**Comment by jsdario** [comment]
Still, is there a way to control timeouts and dismissal?
