### ISSUE TITLE
Do not use use status bar height to calculate navbar height on android

### ISSUE THREAD

**Issue by manV** [exponentjs/ex-navigation#55]
Adding Status bar height to Navbar height results in huge Navbar on android. See image below
![screenshot from 2016-09-04 14-25-28](https://cloud.githubusercontent.com/assets/4988376/18229982/c17daa7e-72ab-11e6-8f99-16709b945120.png)

**Comment by tpedersen123** [comment]
@manV Seems to be the same issue as mine? :)
https://github.com/exponentjs/ex-navigation/issues/49

**Comment by manV** [comment]
didn't see that. will close this issue in favor of #49

**Comment by tpedersen123** [comment]
:-) 

@manV I hope that #54 will be the answer to our problems.
