### ISSUE TITLE
react-native missing from dependencies

### ISSUE THREAD

**Issue by ptomasroos** [exponentjs/ex-navigation#6]
Its referenced in multiple places like:
https://github.com/exponentjs/ex-navigation/blob/master/src/ExNavigationProvider.js#L7-L10

https://github.com/exponentjs/ex-navigation/blob/master/src/ExNavigationBadge.js
https://github.com/exponentjs/ex-navigation/blob/master/src/ExNavigationBar.js
https://github.com/exponentjs/ex-navigation/blob/master/src/ExNavigationStackItem.js
https://github.com/exponentjs/ex-navigation/blob/master/src/ExNavigationTab.js

ect ect

**Comment by skevy** [comment]
It shouldn't be a dependency, it should be a peer dependency. Fixed in f6673f4ba4a19212529575b9c319549663d9ff64.
