### ISSUE TITLE
Update docs with alternative route config

### ISSUE THREAD

**Issue by grabbou** [exponentjs/ex-navigation#62]
Hey,

Going through the source code I've discovered this to be an alternative way of declaring route config:
```js
const Router = createRouter(() => ({
  home: () => ({
    render: Router._makeRoute(HomeScene),
    config: {
      navigationBar: {
        title: 'Home',
      },
    },
  }),
}));
```

In this case, I am calling `_makeRoute` since when object is passed, it's not called as in other cases. Anyways, I think it would be cool to document it (or add to an examples) since many people might prefer to have config in one place, instead of looking into every scene separately for details.

Happy to PR, just wondering what's your idea on that

**Comment by chirag04** [comment]
@brentvatne actually gave me an example y you would want to use `config`. I can't find it and not sure y would you use `config`. If we are to document this I think we should document the usecase also otherwise it would confuse more people.

@grabbou you can have navigationBar with title on the HomeScene.

```
function HomeScene(props) {
}
HomeScene.route = {
    navigationBar: {
       title: 'Home',
    }
};
```

**Comment by grabbou** [comment]
@chirag04 yup, all I am saying is that for me it's just easier to work on the app when the `route` configuration is in one place (in this case, a file where `createRouter` is called) instead of being defined in each scene file separately, as in the example demonstrated by you.

If both ways are supported, they should be IMO documented, otherwise it's not clear why they are there :)

**Comment by brentvatne** [comment]
I don't like how we're using a private api (makeRoute) here. If this is really important, we should make it possible to pass in `component` alongside `config`, where the `component` passed in gets wrapped by `makeRoute` internally -- closing this issue but a PR would be welcome!
