### ISSUE TITLE
How to make SignOut-button in navigationBar listen to Redux store?

### ISSUE THREAD

**Issue by michaelswe** [exponentjs/ex-navigation#64]
I want a signout-button visible to the right in the navigationBar of my main screen. I didn't manage to get hold of this.props.. from within the static route object in my view.

Ended up writing a connected component which I render from navigationBar.renderRight. Is the below an overly complicated solution, or is it the way to go?

    class _SignOutButton extends React.Component {
      render() {
        if(!this.props.isLoggedIn) return null;

        return (
          <TouchableOpacity onPress={this._onPress}>
            <Text>Sign out</Text>
          </TouchableOpacity>
        );
      }
      _onPress = () => this.props.dispatch(AuthenticationState.LogoutAction());
    }

    const SignOutButton = connect(
      state => ({
        isLoggedIn: AuthenticationSelectors.isLoggedIn(state)
      })
    )(_SignOutButton);

**Comment by ptomasroos** [comment]
I think this seems fine. Very similar to what we're doing on redux / ex-navigation
