### ISSUE TITLE
Warning: You passed a non-serializable value as route parameters. This may prevent navigation state from being saved and restored properly.

### ISSUE THREAD

**Issue by laclance** [exponentjs/ex-navigation#66]
Passing a ListView dataSource through route params produces:

> Warning: You passed a non-serializable value as route parameters. This may prevent navigation state from being saved and restored properly.

**Comment by satya164** [comment]
This is expected. You should only have serialisable values in route params, e.g. - plain objects, arrays, string, number, boolean etc.

**Comment by brentvatne** [comment]
@satya164 - @skevy and I discussed this and we think we should make it possible to disable this warning, in case people don't care about serialization

**Comment by satya164** [comment]
@brentvatne Ah, ok then

**Comment by chirag04** [comment]
@brentvatne I feel we should discourage people from using non-serializable value in route params.

In this particular case, why not send the list data as route param and generate the dataSource from that. I don't see the reason for passing dataSource directly. I doubt there is any significant performance gains.

**Comment by laclance** [comment]
Yes I have done that thanks.

**Comment by chirag04** [comment]
@laclance feel free to close this :)

**Comment by brentvatne** [comment]
Discouraging is fine but we should also make it possible for people to say that they don't care :) @chirag04

**Comment by ide** [comment]
What do you think about adding custom serializers/deserializers? For example say that you have a `Symbol` object in your route parameters and don't want to jump through too many hoops but still want route (de)serialization for deep linking. You'd write something like:

```js
function serializeRouteParameters(params) {
  let serializedSymbol;
  switch (params.paramThatIsSymbol) {
    case Symbol.foo: serializedSymbol = 'foo'; break;
    case Symbol.bar: serializedSymbol = 'bar'; break;
    default:
      // need to decide what the API would be. do we throw? return false?
      // have DefaultSerializer print today's warning about non-serializable values?
  }

  let newParams = { ...params, paramThatIsSymbol: serializedSymbol };
  return DefaultSerializer.serialize(newParams);
}
```

That said, maybe we do not want to add (de)serialization hooks to ExNavigation. Maybe the solution can be pushed entirely into user space.

Also (de)serialization might be the wrong way of thinking about things. Generally you should put non-serializable values into a data store, then put the ID of that object in the route params, and then pull the serializable values out of the data store using the ID.

**Comment by naoufal** [comment]
@brentvatne Ran into this problem using Realm `Symbols`.  I think @ide's right about deserialization being the wrong way of thinking about things.  Pass an `id` around makes more sense to me and that's how I'll be approaching this.

If you'd still like a way to silence this warning, I'd be happy to PR.

My approach would be adding a `silenceWarning` key to `routeParams` on the [getRoute](https://github.com/exponentjs/ex-navigation/blob/ec8fa74dc3e94e2386ff6d344892d549d2407185/src/ExNavigationRouter.js#L200) method

**Comment by brentvatne** [comment]
@naoufal - added something similar to `createRouter` so you can at least ignore the warning for now! `createRouter({...etc}, {ignoreSerializableWarnings: true})`

**Comment by brunolemos** [comment]
You can do this to ignore specific warnings:

```js
console.ignoredYellowBox = ['Warning: You passed a non-serializable value as route parameters.'];
```

**Comment by laclance** [comment]
What is the reasoning behind only having serializable values in route params? Should I serialize and deserialize dates or is it safe to ignoreSerializableWarnings for dates?

**Comment by chirag04** [comment]
if you have serializable route params, you can do time travel.

**Comment by satya164** [comment]
Or you could save the navigation state in async storage and restore it, which is pretty useful

**Comment by laclance** [comment]
ok cool, thanks guys, Ill probably go with async storage because I am going to need in the future anyway.

**Comment by ide** [comment]
To summarize in closing:

The reason we have this warning is because making all your route parameters serializable means that you have the possibility of turning them into a URL for deep linking. We think that's useful and want to guide people in that direction.

One way you can deal with non-serializable values is to put them in a data store. That data store could be a Redux store, for example, or just a global hash map. You'd then use the key to the data store as your route param, and in your scene component for the route you'd look up the key in the data store. If you're supporting deep links, one of the things you need to do is populate (ex: rehydrate) the data store with that key-value pair when the user opens your app. How you do that is up to you.

If you don't care much about deep links and just want the warning to go away, there's also an option called `ignoreSerializableWarnings` that you can pass into the router constructor or `createRouter`. See https://github.com/exponentjs/ex-navigation/issues/66#issuecomment-250850286
