### ISSUE TITLE
[question] custom navbar

### ISSUE THREAD

**Issue by vonovak** [exponentjs/ex-navigation#67]
just a quick question - is ex-navigation planning to support custom navbar?
I'd like to be able to use the provided one for ios and use ToolbarAndroid with different scene animations on android.

Thanks!

**Comment by chirag04** [comment]
you can pass in your own implementation of the navbar component. 

https://github.com/exponentjs/ex-navigation/blob/master/src/ExNavigationStack.js#L450

**Comment by jsdario** [comment]
Is there around an example on how to do this?

**Comment by vonovak** [comment]
I'll try to post a gist in a few days. Basically you pass the navbar
component as a prop when creative navigationStack - see the linked code.

**Comment by vonovak** [comment]
@jsdario there it is: https://gist.github.com/vonovak/81d33b0fa55a5f77e9169d143e4293eb
It's still a wip but should already work well
