### ISSUE TITLE
Bug when going back from screen in stack with SlidingTabView

### ISSUE THREAD

**Issue by OwenFlood** [exponentjs/ex-navigation#70]
![](http://i.giphy.com/l0MYRTrUHMDV0NZ3W.gif)

**Comment by brentvatne** [comment]
cc @satya164

**Comment by satya164** [comment]
Hey @OwenFlood , do you have a simple example project which I can try?

**Comment by brentvatne** [comment]
@satya164 - I'll repro it for you, gimme a few mins

**Comment by satya164** [comment]
@brentvatne cool. thanks a lot

**Comment by brentvatne** [comment]
@satya164 - check this out: https://github.com/exponentjs/rnplay/tree/demo-bug-satya (the demo-bug-satya branch has the required code)

repo:
- go to explore screen
- tap the black button in the middle
- tap the picks tab
- press the back button
