### ISSUE TITLE
Support NavigateTransitioner events in ExNavigationStack

### ISSUE THREAD

**Issue by mnichols** [exponentjs/ex-navigation#73]
Recently the react-native team added two important events to `NavigationTransitioner`. See [here](https://github.com/facebook/react-native/blob/master/Libraries/NavigationExperimental/NavigationTransitioner.js#L37-L38).
Can the `onTransitionStart` and `onTransitionEnd` events be supported in the `ExNavigationStack` props to pass through into its `NavigationTransitioner`? eg,
```
    render() {
        return (
            <NavigationProvider router={ router }>
                <StackNavigation
                    initialRoute={ router.getRoute('home') }
                    onTransitionEnd={ doStuff }
                />
            </NavigationProvider>
        )
    }
```
This affordance would more easily let next steps avoid conflicting with current route transitions.
See #32 for an example of the problem of knowing 'when' a transition is completed.

Here is my local mod to `ExNavigationStack` that works:
```
  render() {
    const navigationState: ?Object = this.props.navigationState;

    if (!navigationState) {
      return null;
    }

    return (
      <NavigationTransitioner
        style={styles.container}
        navigationState={navigationState}
        render={this._renderTransitioner}
        configureTransition={this._configureTransition}
        onTransitionEnd={ () => { this.props.onTransitionEnd() } }
      />
    );
  }
```

Lemme know if you'd rather a PR (I dont see any currently)

**Comment by brentvatne** [comment]
good call, thanks! merged
