### ISSUE TITLE
Version 1.5.9 of this package is not Flow clean with Flow 0.32.0

### ISSUE THREAD

**Issue by bolinfest** [exponentjs/ex-navigation#86]
One thing that I do in Nuclide that works with Node/Flow:

```
import invariant from 'assert';
```

This introduces `invariant()` in scope, which Flow likes, while providing the desired runtime behavior of `invariant()` without having to add anything to your `package.json`.

**Comment by brentvatne** [comment]
Tracking in #87 -- a PR would be very welcome :)
