### ISSUE TITLE
Customize transitions

### ISSUE THREAD

**Issue by samuelkraft** [exponentjs/ex-navigation#90]
Is it possible to add custom transitions? I'd like to mimic the default iOS slide & modal transitions and not have the fade/scale effect. Is there any example of this or do you have a general idea how one can accomplish this?

**Comment by chirag04** [comment]
@samuelkraft It is possible to provide your own transition styles like this:
```
YourScene.route = {
    styles: {
        configureTransition: () => { ...your styles },
    },
    navigationBar: { .... },
}
```

Refer: https://github.com/exponentjs/ex-navigation/blob/master/src/ExNavigationStack.js#L44-L46

I would recommend sending a PR tho if you think what we have now can be improved/mimic default.

**Comment by samuelkraft** [comment]
Thanks, this repo is just importing the default transition from NavigationExperimental now right? Looks like the actual transform/opacity stuff is done in https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/NavigationExperimental/NavigationCardStackStyleInterpolator.js

**Comment by samuelkraft** [comment]
And a semi-related question: it is currently not possible to push a route with transparent background and have the previous one show in the back (think modal). Is this something that's on the roadmap?

**Comment by chirag04** [comment]
modals are supported, check the examples directory. Although currently background color defaults to white. (https://github.com/exponentjs/ex-navigation/blob/79d9a6e4d787a60d76b15936f3a252e453eb92df/src/ExNavigationStackItem.js#L75). I think you can override it to `transparent` if you need tho.

About default transition: This repo overrides some styles from NavigationExperiemetnal. Refer: https://github.com/exponentjs/ex-navigation/blob/79d9a6e4d787a60d76b15936f3a252e453eb92df/src/ExNavigationStyles.js#L34

**Comment by samuelkraft** [comment]
Thank you. Submitted a PR for FloatVertical since @brentvatne already did the Horizontal one.

**Comment by chirag04** [comment]
awesome 👍
